version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: fantastic
      MYSQL_DATABASE: social 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"    
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"  
    ports:
      - "3306:3306"

  back:
    build:
      context: .
    depends_on:
      - db
    volumes:
      - ./:/app
